### ISSUE TITLE
VGG16 performance check

### ISSUE THREAD

**Issue by jimmy-adams** [SamsungLabs/Sparse-Multi-DNN-Scheduling#1]
Hello,
I try running the VGG16 on Eyeriss-v2 simulator, and got the layerwise latency. Taking vgg16_blcok4_sparse20 as the example, the result shows the latency of 0.00719452 from the generated csv. Is the time unit millisecond or second?
Thanks alot

**Comment by os-hxfan** [comment]
Thanks for your interest.  The time scale is second.
