### ISSUE TITLE
Dataflow configuration related questions

### ISSUE THREAD

**Issue by jimmy-adams** [SamsungLabs/Sparse-Multi-DNN-Scheduling#2]
Dear Dr,
Thanks alot for your design to simulate the [eyeriss](https://github.com/SamsungLabs/Sparse-Multi-DNN-Scheduling/blob/main/hw_simulator/cnn_eyerissv2/hw_eyerissv2.py). I successfully run and get the reasonable latency. But back to the original paper, Eyeriss v2 should support different dataflow, such as the OS and WS. Is it possible to configure the dataflow with the current python script? or I need to define it my self? if needing extra efforts to finish the define job. can you provide me some further details or ideas about the how to extend it ?

Best Regards

**Comment by os-hxfan** [comment]
Thanks a lot for your interest. @jimmy-adams 
Sorry for the delayed reply.

Our simulator is based on this [eyeriss-v2](https://github.com/karthisugumar/CSE240D-Hierarchical_Mesh_NoC-Eyeriss_v2) design. If you want to support different dataflow, you can base on their design to extend the hardware, then build a simulator on your customized eyeriss-v2 hardware based on simulation waveform.  Once you got simulator, you can easily plug in into our tool to get results.
